config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'

  resources :users
  resources :hairstyles
  resources :stylists
  resources :salons, only: [:index]
  resources :appointments

  
  post "/makeappointment", to: "appointments#make_appointment", as: "make_appointment"

  


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/appointment.rb
class Appointment < ApplicationRecord
  belongs_to :customer
  belongs_to :hairstyle
  # belongs_to :salon

  accepts_nested_attributes_for :customer
end

app/models/customer.rb
class Customer < ApplicationRecord
    has_many :appointments
    has_many :hairstyles, through: :appointments
    has_many :stylists, through: :hairstyles
end

app/models/hairstyle.rb
class Hairstyle < ApplicationRecord
  has_many :appointments
  belongs_to :stylist
end

app/models/salon.rb
class Salon < ApplicationRecord
end

app/models/stylist.rb
class Stylist < ApplicationRecord
  has_many :hairstyles
  has_many :appointments, through: :hairstyles
  has_many :customers, through: :appointments
  belongs_to :salon
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
    
    def index
        @appointments = Appointment.all 
    end

    def show
        @appointment = Appointment.find(params[:id])
    end

    def make_appointment
        customer = Customer.find_or_create_by(name: params[:customer][:name])
        hairstyle = Hairstyle.find_by(id: params[:appointment][:hairstyle_id])
        salon = hairstyle.stylist.salon
        date = Time.new(params[:appointment]["time(1i)"].to_i, params[:appointment]["time(2i)"].to_i, params[:appointment]["time(3i)"].to_i, params[:appointment]["time(4i)"].to_i, params[:appointment]["time(5i)"].to_i)
        appointment = Appointment.create(date: date, customer_id: customer.id, hairstyle_id: hairstyle.id, salon_id: salon.id)
        if appointment.valid?
            flash[:success] = 'Thank you for your appointment!'
            redirect_to appointment_path(appointment)
        else
            flash[:errors] = appointment.errors.full_messages
            redirect_to new_appointment_path
        end 
    end


    def destroy
        Appointment.destroy(params[:id]) 
        redirect_to salons_path
    end

    private
    
    def createAppointmentParams
        params.require(:appointment).permit(:date, :customer_id, :hairstyle_id, :salon_id)
    end

    def updateAppointmentParams
        params.require(:appointment).permit(:date, :customer_id, :hairstyle_id, :salon_id)
    end

end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
end

app/controllers/hairstyles_controller.rb
class HairstylesController < ApplicationController
    def index
        @hairstyles = Hairstyle.all 
    end

    def show
        @hairstyle = Hairstyle.find(params[:id])
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
  end
end

app/controllers/salons_controller.rb
class SalonsController < ApplicationController
    def index
    end
end

app/controllers/stylists_controller.rb
class StylistsController < ApplicationController

    def index
        @stylists = Stylist.all
    end

    def show
        @stylist = Stylist.find(params[:id])
        @hairstyles = @stylist.hairstyles
        @appointment = Appointment.new
    end

    def destroy
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/appointments/_form.html.erb
<% if @appointment.errors.full_messages.length > 0 %>
  <h2><%= pluralize(@appointment.errors.full_messages.length , "error") %> prohibited this appointment from being created:</h2>
  <ul>
    <% @appointment.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<%= form_with model: @appointment, url: make_appointment_path do |f| %>
        
    Style: <%= f.collection_select(:hairstyle_id,  @stylist.hairstyles, :id, :style) %><br>
    <%= fields_for :customer do |customer| %> 
    <%= customer.label :name %>
    <%= customer.text_field :name %><br>
    <% end %>
    Select An Appointment Date: <%= f.datetime_select :time%><br>
    
    <%= f.submit %>
<% end %>

app/views/appointments/index.html.erb
<div class="appoiments-details-container">
<div class="hair-salons-img">
        <%= image_tag("salon3.jpg")%>
    <div>
    <div class="appoiments-details">
            <%# <h2>Stylist details</h2> %>
            <div class="row">
                <% @appointments.each do |appointment| %>
                    <div class="appoiments-col-2">
                        <h1><%= link_to appointment.customer.name.capitalize, appointment_path(appointment.id) %></h1><br>
                        <h2><%= link_to appointment.date.strftime("%d/%m/%Y - %k:%M"), appointment_path(appointment.id) %></h2>
                    </div>
                <% end %>
            </div>

    <div class="space-button">
        <%= link_to  "Back", root_path,  class: "hero-btn-1" %>
    </div>
</div>

app/views/appointments/new.html.erb
<%= render partial: "form" %>

app/views/appointments/show.html.erb
<div class="appoiments-details-container">
<div class="hair-salons-img">
        <%= image_tag("hair-salons-img.jpg")%>
    <div>
 <div class="appoiments-details">
        <div class="row">
            <div class="appoiments-col-2">  
                <h1><%= @appointment.customer.name.capitalize %></h1>
                <h2><%= @appointment.date.strftime("%d/%m/%Y - %k:%M") %></h2>
                <h2><%= @appointments %></h2>     
            </div>     
        </div>

    <%= link_to 'Back', appointments_path, class: "hero-btn-1" %>
    <%= link_to 'Delete', appointment_path(@appointment), class: "hero-btn-1", method: :delete %>
   
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ely's</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>

    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,200;0,300;0,400;0,600;0,700;1,200;1,400&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>

    <%= yield %>
    <%= render 'shared/footer' %>




<!-----------JavaScript for Toggle Menu------------>
    <script>
        var navLinks = document.getElementById("navLinks");

        function showMenu() {
            navLinks.style.right = "0";
        }

        function hideMenu() {
            navLinks.style.right = "-200px";
        }




// JavaScript for Contact-Form

        var form = document.getElementById("my-form");
            
        async function handleSubmit(event) {
        event.preventDefault();
        var status = document.getElementById("status");
        var data = new FormData(event.target);
        fetch(event.target.action, {
            method: form.method,
            body: data,
            headers: {
                'Accept': 'application/json'
            }
        }).then(response => {
            status.innerHTML = "Thanks for your submission!";
            form.reset()
        }).catch(error => {
            status.innerHTML = "Oops! There was a problem submitting your form"
        });
        }
        form.addEventListener("submit", handleSubmit)

    </script>

    
  </body>
  </html>

app/views/pages/home.html.erb
<% content_for(:navbar_class, "navbar-home") %>
<% content_for(:footer_class, "footer-home") %>

<div class="banner" id="home">
  <div class="text-box"> 
    <h1>Ely's</h1>
    <p>Ely's beauty salon has been part of London’s hair scene since 2015,
     and we wanted to give you an illustrative snapshot into the story that we are
     so proud of.</p>
     <%= link_to  "Our Stylists", stylists_path, class: "hero-btn" %>
  </div>
</div>

<div class="about-us-container">
    <div class="aboutUs" id="about-us">
        <h2>About Us</h2>

         <div class="row">
            <div class="aboutUs-col">
                <p><em>Ely's</em> has been part of London’s hair scene since 2015, 
                    and we wanted to give you an illustrative snapshot into the story that we are so proud of. 
                    Our philosophy for nurturing and developing raw talent which we began at our first salon in Sydney Street. 
                    We opened one of the most celebrated names in hair and beauty, Elena & Chuk’s is proud of its heritage 
                    and stellar team, many of which have been with us for over 5 years. We would like to thank you, 
                    as well as the loyal press, for supporting our creative journey to becoming one of the 
                    best styling teams in the capital.
                </p>
                <p> 
                    The new flagship is our vision of what tomorrow's salon will look like.
                    Imagine innovative design, state-of-the-art technology and modern menus trailblazing,
                    with a botanical-inspired philosophy which stays true to our classic, luxury roots. 
                    So while you can plug into your personalised iPad programme, read a digital magazine, 
                    check emails, book appointments. Our plant-based menu including Hari's Herb Bar, 
                    Organic Colour Counter and natural magic washes, combined with our expertise, 
                    will simply deliver on great hair.
                </p>        
            </div>
        </div>

        <div class="stylists">
            <h2>Meet our stylists</h2>

            <div class="row">
            <div class="stylists-col">
                    <%= image_tag("adao.jpg")%>
                    <div class="layer">
                        <h3>Adao</h3>
                    </div>
                </div>

                <div class="stylists-col">
                      <%= image_tag("dorothy3.jpg")%>
                    <div class="layer">
                        <h3>Dorothy</h3>
                    </div>
                </div>

                <div class="stylists-col">
                   <%= image_tag("lery.jpg")%>
                    <div class="layer">
                        <h3>Lery</h3>
                    </div>
                </div>
               
                <div class="stylists-col">
                     <%= image_tag("mina.jpg")%>
                    <div class="layer">
                        <h3>Mina</h3>
                    </div>
                </div>

                <div class="stylists-col">
                    <%= image_tag("gbenga.jpg")%>
                    <div class="layer">
                        <h3>Gbenga</h3>
                    </div>
                </div>

                <div class="stylists-col">
                    <%= image_tag("july.jpg")%>
                    <div class="layer">
                        <h3>July</h3>
                    </div>
                </div>
            </div>
        </div>
    <%= link_to 'Booked Appointments', appointments_path , class: "hero-btn-1"%> 
 </div>


    <div class="facilities">
        <h1>Our services</h1>
        <p>Please have a look at out services.We hope you will love our stylists.</p>

        <div class=row>
            <div class="facilities-col">
                <%= image_tag("sp.jpg")%>
                <h3>Side Parting</h3>
                <p>To create a side part, hold the tip of a comb down towards the scalp. ... 
                   Some look better with a diagonal direction to offset the side part, 
                   while others will pull hair straight back or down to the other side.
                </p>
            </div>

             <div class="facilities-col">
                <%= image_tag("high.jpg") %>
                <h3>High Top</h3>
                <p>The high top fade haircut may have peaked in the late 1980s and early 
                   1990s but it is back again and here to stay. The cut has come a long 
                   way from Kid of Kid 'n Play's unforgettable look.
                </p>
            </div>

            <div class="facilities-col">
                <%= image_tag("wavey.jpg")%>
                <h3>Beach Waves</h3>
                <p>Beach hair is essentially the opposite of dull, lifeless hair. 
                   It's got volume, texture, definition. It looks effortless—artfully 
                   suspended in perfect form without any effort whatsoever.
                </p>
            </div>


            <div class="facilities-col">
                <%= image_tag("buzzed.jpg")%>
                <h3>Buzz Cut</h3>
                <p>If you have a lean face, strong jaw, and good cheekbones, 
                   you're a shoo-in for the buzz cut look. Just be wary that if 
                   your forehead is already on the larger side, or your jaw is 
                   something you don't want to be drawing attention to, tightly 
                   cropped hair will probably not be for you.
                </p>
            </div>

            <div class="facilities-col">
                <%= image_tag("dreads1.jpg")%>
                <h3>Dreads</h3>
                <p>Dreads have always been worn to make a statement. For many, 
                   they're spiritual and they symbolize the letting go of material 
                   possessions. For others, they're political and a way to rebel 
                   against conformity and the status quo. Some just like the way they look.
                </p>
            </div>

            <div class="facilities-col">
                <%= image_tag("fade.jpg") %>
                <h3>Fade</h3>
                <p>Go for a blended hairstyle if you want to 
                   leave some length on the top, sides, and back. Most men's haircuts involve 
                   some sort of taper, and if you want a clean, thick, classic cut, a taper is the way to go.
                </p>
            </div>         
        </div>
    </div>


    <!--------------- testimonials ------------------>

    <div class="testimonials">
        <h1>What Our Clients Says</h1>

        <div class="row">
            <div class="testimonial-col">
                <%= image_tag("img.jpg") %>
                <div>
                    <p>
                       I cannot even begin to describe how lovely my experience was. 
                       From check-in to check-out, I felt like an absolute princess. 
                       What a hidden gem of a salon! Maria did an outstanding color 
                       correction and also freshened up my haircut with some chic fringe bangs.
                    </p>
                    <h3>Christine Berley</h3>
                    <i class="fas fa-star"></i>
                    <i class="fas fa-star"></i>
                    <i class="fas fa-star"></i>
                    <i class="fas fa-star"></i>
                    <i class="far fa-star"></i>
                </div>
            </div>

             <div class="testimonial-col">
                <%= image_tag("img1.jpg")%>
                <div>
                    <p>
                      Just wow!! I had a warm welcome by all the stylists at the salon. 
                      The hair wash and head massage by Joe was bliss, it was extremely 
                      relaxing and I went into heaven. They make the whole experience so peaceful. 
                    </p>
                    <h3>David Grey</h3>
                    <i class="fas fa-star"></i>
                    <i class="fas fa-star"></i>
                    <i class="fas fa-star"></i>
                    <i class="fas fa-star"></i>
                    <i class="fas fa-star-half-alt"></i>
                </div>
            </div>
        </div>
    </div>

    <!--------------Call to action -------------------->
    <div class="cta">
        <h1>Make reservations or find out more details about <br>
           our salon by just filling out this form.
        </h1>
        <%= link_to "Contact Us", salons_url, class: "hero-btn"  %>
    </div>

app/views/salons/index.html.erb
<footer id="contact-us" class="contact-us">
        <h2>Contact Us</h2> 
        <div class="footer-container">

          <form action="https://formspree.io/f/mqkwzgdw" method="POST" id="my-form">
            <div class="form-group">
                <label for="firstName">First Name</label>
                <input type="text" id="firstName" name="firstName">
            </div>

            <div class="form-group">
                <label for="lastName">Last Name</label>
                <input type="text" id="lastName" name="lastName">
            </div>

            <div class="form-group">
                <label for="email">Email</label>
                <input type="email" id="email" name="email">
            </div>

            <div class="form-group">
                <label for="message">Message</label>
                <textarea name="message" id="message" cols="30" rows="10"></textarea>
            </div>

           <button class="button" type="submit" value="submit">Send</button>
        </form>
    </div>
    <div id="status"></div>
    </footer>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer <%= yield(:footer_class)%>">
    <h4>Follow Us</h4>
    <p>This west London stalwart is recognisable by its bold red frontage, with esteemed salons stretching <br> 
       from Parsons Green to Notting Hill. The new Fulham outpost encapsulates everything we love <br>
       about Ely's and is styled with a verdant living wall and unique hair Herb Bar.
    </p>
    <div class="icons">
        <i class="fa fa-facebook"></i>
        <i class="fa fa-twitter"></i>
        <i class="fa fa-instagram"></i>
        <i class="fa fa-linkedin"></i>
    </div>
    <p class="copyright"> Made by <i class="far fa-copyright"></i></i><em>Ely</em></p>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon <%= yield(:navbar_class)%>">
  <%= link_to root_path, class: "navbar-brand" do %>
    <%= image_tag "https://www.pngkit.com/png/detail/79-790674_instyle-beauty-salon-hairdresser-beauty-hair-salon-logo.png" %>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation" onclick="showMenu()">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="nav-links" id="navLinks">
    <ul class="navbar-nav mr-auto">
      <i class="fa fa-times" onclick="hideMenu()"></i>
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to "Home", root_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "BookYourStilist", stylists_path, class: "nav-link"%>
          </li> 
          <li class="nav-item">
            <%= link_to "AboutUs", "#about-us", class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "ContactUs", salons_url, class: "nav-link" %>
          </li>
        
          <li class="nav-item dropdown">
            <%= image_tag "https://avatars.githubusercontent.com/u/55464617?v=4", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>

            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
              <%= link_to "Appoiments", appointments_path, class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
            </div>
       
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/stylists/index.html.erb
<div class="container-stylists">
  <div class="banner-stylists" id="banner-stylists">
    <div class="text-box-stylists"> 
      <h1>Book your favourite <br> stylist</h1> 
      <ul>
        <% @stylists.each do |stylist| %>
          <li><%= link_to stylist.name, stylist_path(stylist) %></li>
        <% end %>
      </ul>
      <%# <%= link_to  "Our Stylists", stylists_path, class: "hero-btn" %> 
    </div>
  </div>
<%# </div> %>

app/views/stylists/show.html.erb
<div class="stylist-details">
    <div class="stylist-container">
        <h1><%= @stylist.name %></h1>
        <h2> Years of <br> experience: <%= @stylist.years_of_experience %></h2>
        <h2> Occupation: <br> <%= @stylist.occupation %></h2>
    </div>



    <div class="stylist-details-price-and-style">
        <% @hairstyles.each do |hairstyle| %>
        <ol> 
            <li>
                <h2><%= hairstyle.style %></h2>
                <h3>Price: £<%= hairstyle.price %></h3>
            </li>
            </ol>
        <% end %>
    </div>

    <div class="stylist-appointment-container">
        <div class="stylist-appointment-form">
            <%= render 'appointments/form', :appointment => @appointment, :stylist => @stylist %>
        </div>
    </div>


<%= link_to  "Back", stylists_path,  class: "hero-btn-1" %>
<%= link_to 'Booked Appointments', appointments_path ,  class: "hero-btn-1"%>

</div>